file-box:
  anonymous:
    enabled: true
  system:
    anonymous-upload-enabled: true
    share-notice-enabled: true
  storage-spaces:
  - name: default
    path: ./uploads
    max-size: 1GB
    allow-anonymous: false
  - name: test
    path: ./test-uploads
    max-size: 1GB
    allow-anonymous: false
  - name: opt-data
    path: /opt/file-box/data
    max-size: 2GB
    allow-anonymous: false
  - name: anonymous
    path: /opt/file-box/anonymous
    max-size: 2GB
    allow-anonymous: true
  - name: shared
    path: /opt/file-box/shared
    max-size: 1GB
    allow-anonymous: false
  users:
  - username: admin
    password: $2a$10$xr50sWtX1iVBIjg.XIGjbOrl9CuUYBrJRc9k0BsfwrgtLNFDlo/4m
    role: ADMIN
    storage-spaces:
    - default
    - test
    - opt-data
    - anonymous
    - shared
  - username: manager
    password: $2a$10$CXh4tIvgLAXnYPIWDQGoaONfMVttGM42aEdup7zLgRoA2JJe/I06a
    role: MANAGER
    storage-spaces:
    - default
    - test
    - opt-data
    - anonymous
    - shared
  - username: user
    password: $2a$10$9xN45k/0AKvyoWCK/DengOT0dcfV382ctJhJo3COoG2ncgPMLjmne
    role: USER
    storage-spaces:
    - default
    - test
    - opt-data
    - anonymous
    - shared
  - username: use2
    password: $2a$10$09iCbH7p6Z4DVXFXkk5rC.PxPOpXrgu5GftRKYAJPuWBUEM/k1chi
    role: USER
    storage-spaces:
    - default
    - test
    - opt-data
