file-box:
  anonymous:
    enabled: false
  system:
    anonymous-upload-enabled: false
    share-notice-enabled: true
  storage-spaces:
  - name: default
    path: ./uploads
    max-size: 1GB
    allow-anonymous: true
  - name: test
    path: ./test-uploads
    max-size: 1GB
    allow-anonymous: false
  - name: opt-data
    path: /opt/file-box/data
    max-size: 2GB
    allow-anonymous: true
  - name: anonymous
    path: /opt/file-box/anonymous
    max-size: 2GB
    allow-anonymous: true
  - name: shared
    path: /opt/file-box/shared
    max-size: 1GB
    allow-anonymous: true
  users:
  - username: admin
    password: $2a$10$xr50sWtX1iVBIjg.XIGjbOrl9CuUYBrJRc9k0BsfwrgtLNFDlo/4m
    role: ADMIN
    storage-spaces:
    - default
    - test
    - opt-data
    - anonymous
    - shared
  - username: testuser
    password: $2a$10$PbHqf/Ox1EQxcU1Wvmc7MurpVD1bCvcrAwvabssOzL208mL2FATSC
    role: USER
    storage-spaces:
    - default
    - test
    - opt-data
  - username: aaa
    password: $2a$10$8DYM4dyywOumXLY6BlKgc.RtSzJmRt3KOL5LIy9FF/0xMpKyDJHN.
    role: USER
    storage-spaces:
    - default
    - test
  - username: abc
    password: $2a$10$po/BYe.YbecdkZUGcpB.G.OtmvVACnqANluKLL9MULq.47PPhv/8e
    role: USER
    storage-spaces:
    - default
    - test
    - opt-data
  - username: tester
    password: $2a$10$nwY5ZL7L1WfDCDF8yz7zv.1pv1ssK1FzNxpT3N66ue3cUeK3lhkzO
    role: USER
    storage-spaces:
    - default
    - test
